### ISSUE TITLE
Issues not enabled in other repo

### ISSUE THREAD

**Issue by cjbottaro** [LukeYui/launch_modded_eldenring#1]
Hey, just wanted to let you know that GitHub issues aren't enabled for your other repo https://github.com/LukeYui/EldenRingSeamlessCoopRelease so people are just making comments on an existing PR that someone opened a long time ago.

It would probably help a ton to organize and address bugs via proper use of GitHub Issues... 👍

**Comment by yuiamoroll** [comment]
Yeah it's closed because I'm currently not at my PC so can't address bugs and manage it properly. Once I can and am actively working on the mod (not just maintaining it) I'll open it up.
